import './sass/main.scss'

import app from './Components/App.js'
import banner from './Components/Banner.js'
import header from './Components/Header.js'
import main from './Components/Main.js'
import services from './Components/Services.js'
import about from './Components/About.js'
import interactions from './Components/Interactions.js'
import cooperate from './Components/Cooperate.js'
import form from './Components/Form.js'
import map from './Components/Map.js'
import footer from './Components/Footer.js'
import scroll from './Components/scroll.js'
